// export enum MODEL_TYPES {
//     BUILDING = 'BUILDING',
// }

export enum BUILDING_TYPES {
    LIVING = 'LIVING',
    MARKET = 'MARKET',
}

export enum LOCAL_STORAGE_KEYS {
    MODELS = 'MODELS',
}

export enum EVENTS {
    START_BUILDING = 'START_BUILDING',
    CHANGE_BUILDINGS_COORDS = 'CHANGE_BUILDINGS_COORDS',
    ADD_BUILDING = 'ADD_BUILDING',
    CANCEL_BUILDING = 'CANCEL_BUILDING',
}
